services:
  hsdb:
    container_name: hsdb
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  hsnginx:
    container_name: hsnginx
    image: nginx
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - './project:/var/www/html:ro'
      - './config/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - hsphp
  hsphp:
    container_name: hsphp
    build: ./config/docker/php
    #image: php:8.1-rc-fpm-alpine
    volumes:
      - './project:/var/www/html:rw'